logging:
  level:
    ROOT: WARN
    com.cinq: INFO

spring:
  application: brazil-cities-data-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          zk-nodes: localhost
          replication-factor: 1
          min-partition-count: 3
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        brazilCitiesConsumerChannel:
          destination: brazil-cities-topic
          content-type: application/json
          group: demo-consumer-group
          consumer:
            startOffset: latest
            max-attempts: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${environment.db.url}:3306/demo?serverTimezone=UTC&useLegacyDatetimeCode=false&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: ${environment.db.adminpwd}
    hikari:
      auto-commit: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    password: ${environment.db.adminpwd}
    user: root
    schemas: demo
    url: jdbc:mysql://${environment.db.url}:3306?serverTimezone=UTC&useLegacyDatetimeCode=false&rewriteBatchedStatements=true&useSSL=false
  mvc:
    favicon:
      enabled: false

server:
  port: 8096
  servlet:
    session:
      cookie:
        http-only: true

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env", "health", "info", "threaddump", "logfile", "loggers", "custombindings" ]
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false
    kafka:
      enabled: true
  metrics:
    enabled: false

application:
  demo:

environment:
  db:
    adminpwd:
    url: localhost

