logging:
  level:
    ROOT: WARN
    com.cinq: INFO

spring:
  application:
    real-estate-data-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          zk-nodes: localhost
          replication-factor: 1
          min-partition-count: 3
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        realEstateProducerChannel:
          destination: real-estate-topic
          content-type: application/json

application:
  demo:
    source-folder: ./source