logging:
  level:
    ROOT: WARN
    com.cinq: INFO

spring:
  application:
    brazil-cities-data-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          zk-nodes: localhost
          replication-factor: 1
          min-partition-count: 3
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        brazilCitiesProducerChannel:
          destination: brazil-cities-topic
          content-type: application/json

application:
  demo:
    source-folder: ./source